from . import questionnaire_format_wizard
from . import setting
from . import income_doctor_wizard
from . import patient_by_procedure
from . import income_by_procedure
from . import income_by_combo
from . import archive_wizard
from . import edit_patient
from . import completed_reversal
from . import patient_overdue_report
from . import doctor_appointment_report
from . import appointment_cancel_report
from . import user_creation
from . import account_invoice_refund
