{
    'name': 'POS Arabic Receipt V14',
    'summary': 'POS arabic receipt as per the industrial Standard',
    'description': """POS arabic receipt as per the industrial Standard""",
    "version": "14.2.1.1",
    'sequence': 1,
    'email': 'ajmalc6705@gmail.com',
    'website': '',
    'category': 'Point of Sale',
    'author': 'Ajmal',
    'price': 10,
    'currency': 'EUR',
    'license': 'OPL-1',
    "live_test_url": "",
    'depends': ['point_of_sale'],
    'qweb': ['static/src/xml/templates.xml'],
    'data': ['views/pos_receipt_template.xml',
             'views/product_view.xml'
             ],
    'images': ['static/description/main_screenshot.png'],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
