{
    'name': 'Linovate Solution E learning',
    'version': '15.0.1.0.0',
    'summary': 'A module for Manage elearning',
    'description': '',
    'category': 'Website',
    'author': 'Linovate Solution',
    # 'website': "https://techboterp.com",
    # 'company': 'TechbotErp',
    'license': 'LGPL-3',
    'complexity': 'easy',
    'sequence': '-100',
    'images': [],
    'depends': ['base','website_slides','website_profile'],
    'data': [
        # 'security/ir.model.access.csv',
        # 'wizard/user_available_wiz_view.xml',
        'views/slide_channel_view.xml',
        'views/website_slide_templates_homepage_view.xml',
        # 'views/user_view.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
    # 'assets': {
    #     'web.assets_backend': [
    #         'techboterp_user_available/static/src/js/kanban_header_btn.js',
    #     ],
    # },
}
